### ISSUE TITLE
Convert major sections into components

### ISSUE THREAD

**Issue by moorhead212** [COSC481W-2023Fall/planned-out#20]
**MAINTENANCE TASK:** 
We need to convert our major sections into components to simply the code and increase efficiency. Doing this will also reduce issues with merging code in the future. This needs to be completed at the very beginning of the sprint.

**Task:**
Fix/Create the following:
- [ ] Task view card
- [ ] Add task card
- [ ] Calendar card
- [ ] Future cards

**Acceptance Criteria:**
- [ ] Cards are all converted to components
- [ ] Future cards have a template to follow
