### ISSUE TITLE
Tasks Card - Combine Tasks List and Task Add

### ISSUE THREAD

**Issue by moorhead212** [COSC481W-2023Fall/planned-out#22]
**User story:**
As a user when I click "Add a task" button I should be prompted to input the information relevant to the task I want to add, this should also go away when I've added my new task. 

- **Persona:** A user wishing to add a new task to my list. 
- **Fix/Feature:** Simplifying the UI to operate in a consistent manner.  
- **Business Value:** A clean and functional UI will attract and keep more users.

**Tasks:**
- [x] Hide "Add task" by default
- [x] Unhide "Add task" on add a task click
- [x] Hide "Add task" on submit click

**Acceptance criteria:**
- [x] The task add section should be hidden by default
- [x] When the user clicks on the 'Add task' button, the task add section should appear
- [x] When the user submits the task, the task add section should disappear
