### ISSUE TITLE
Register User Page - Backend/Database

### ISSUE THREAD

**Issue by moorhead212** [COSC481W-2023Fall/planned-out#24]
**User Story:** 
As a user I want to be able to register and store my information securely for future log in attempts.

- **Persona:** A user trying to register an account.
- **Feature:** Storage of information in a safe and responsible manner.
- **Business Value:** New users signing up for the product - and maintaining their trust through responsible handling of their data.

**Tasks:**

_Backend_
- [ ] Regex username to not contain special characters
- [ ] Make sure confirm password matches password
- [ ] Hash password before submitting
- [ ] Regex email to only allow a valid email

_Database_
- [ ] Check to see if username exists in database, if so return a "user already exists"
- [ ] Check to see if email exists in database, if so return a "email already exists"
- [ ] When there are no errors in data, send data to database

**Acceptance Criteria**
1. Passwords and usernames are encrypted in database for security
2. Email storage in cluster
3. Have collections for each user to store their tasks and etc.
4. Backend error case handling
