### ISSUE TITLE
Login Page - Frontend

### ISSUE THREAD

**Issue by moorhead212** [COSC481W-2023Fall/planned-out#25]
**User Story:**
As a user, I would want my tasks to be separate from all other user's and would like to be able to login to my account.

- **Persona:** A user that has been logged out, or never logged in previously. 
- **Feature:** A login page for the user to input their credentials and have them checked against registered users in order to access their personal site information and tasks. 
- **Business Value:** Allowing users to log in lets us store data uniquely to specific users. 

**Tasks:**
- [x] Create a login page
- [x] Username/Password Inputs
- [x] A link when user does not have an account yet (Brings user to Register User page)
- [x] Forgot password link
- [x] Popup if information missing/invalid

**Acceptance Criteria:**
If a user enters their credentials they are sent to the backend for validation. if they are valid, the user will be forwarded to their home page. 
If a user is missing information a pop-up warning will appear correcting the behavior.

**Comment by doormatt65** [comment]
Lots and lots of issues happened when we attempted to revert our accidental merge. Redid whole PR on branch #38
