### ISSUE TITLE
Login Page - Backend/Database

### ISSUE THREAD

**Issue by moorhead212** [COSC481W-2023Fall/planned-out#26]
**User Story:** As a user I would like to be able to log in to my account that I have stored for this product. 

**Tasks:**
_Backend_
- [ ] Hash the password and match it up with the password that was already hashed after Username given is in the database.
- [ ] If the passwords match, go to home page, else give prompt to user (via frontend) saying either username or password is invalid.
- [ ] If the user does not remember their password, send an email to the user to change password based on a regex of either an email or username provided.

_Database_
- [ ] Check for password and username matching
- [ ] Find email/username in database and email when changing password
- [ ] Change password upon password change

**Acceptance Criteria**
1. Grab information from the Database to compare with information gathered in the frontend
2. Route users to home page if correct user information is entered
3. Forgot password section
4. Password update in database
