### ISSUE TITLE
Settings Page - Shell

### ISSUE THREAD

**Issue by moorhead212** [COSC481W-2023Fall/planned-out#27]
**MAINTANENCE TASK:**
As the development team, we need to have a settings page shell in order to build other pages onto.

- **Persona:** Dev team
- **Feature:** A standardized page to place other components onto.
- **Business Value:** Keeps the UI clean and allows us to build user trust.

**Tasks:**
- [x] Create main page with navigation bar
- [x] Create main card on page
- [x] Create pagination side-nav bar

**Acceptance Criteria:**
- [x] A settings button should be added to the site's navigation bar
- [x] When clicking on the settings button, the settings page should open
- [x] There should be two sections: one is a list of all settings subpages, and the other is the settings for the current subpage
