### ISSUE TITLE
Settings: Account Security - Front end

### ISSUE THREAD

**Issue by moorhead212** [COSC481W-2023Fall/planned-out#28]
**User story:**
User Information should be securely stored in the database to protect user information

**- Persona:** User needing or wanting to change password information. 
**- Feature:** User should be able to update their password as needed.
**- Business Value:** Allowing users to change passwords allows for a more secure service.

**Tasks:**
- [x] Create input box for email
- [x] Create input box for old password (to verify)
- [x] Create input box for new password
- [x] Create input box for verify new password
- [ ] New password is encrypted (or hashed) and stored securely in database before passing to backend

**Acceptance Criteria:**
1. User information (password, email?) packaged and sent via API call to backend/database.

Dependency: 
[Settings Page - Shell](https://github.com/orgs/COSC481W-2023Fall/projects/4/views/1?pane=issue&itemId=42822759)

**Comment by tedgravlin** [comment]
Closed with https://github.com/COSC481W-2023Fall/planned-out/commit/6dae493ad4f1876de3ecbedd3b44dc4476acaf0f
