### ISSUE TITLE
Settings: Account Security - Backend

### ISSUE THREAD

**Issue by moorhead212** [COSC481W-2023Fall/planned-out#29]
**User story:**
User Information should be securely stored in the database to protect user information

**- Persona:** User updating password.
**- Feature:** User should be able to update their password as needed with it being updated and stored.
**- Business Value:** User information is stored securely to prevent identity theft

**Tasks:**
- [x] Retrieve the information from Front end using API call
- [x] Send the secured information to the database for storage. 
- [x] User information is encrypted in database (hashed? RSA?)

Acceptance Criteria: 
- [x] New password is encrypted and stored securely in database.

Dependency: 
[Settings Page - Shell](https://github.com/orgs/COSC481W-2023Fall/projects/4/views/1?pane=issue&itemId=42822759)
