### ISSUE TITLE
Settings - Theme customization

### ISSUE THREAD

**Issue by tedgravlin** [COSC481W-2023Fall/planned-out#40]
**User story:**
As a user I should be able to customize the accent color of the website. The theme should also switch automatically based on what my system theme is.

* **Persona:** A user that wants to change the look of the website
* **Feature:** A customization page where the user can change the accent color
* **Business Value:** Allowing users to customize the look of the website makes it more personal, and makes it more likely that they'll continue to use the website.

**Tasks:**
- [x] Add an accent color section
- [x] Populate the accent color section with different color options
- [x] Change the site's colors when an accent color is selected
- [x] Change theme based on system theme

**Acceptance Criteria:**
- [x] There should be multiple different accent colors to choose from
- [x] Clicking on an accent color should immediately change the accent color for the whole site
- [x] The theme (light/dark) should change automatically based on the system theme

Dependencies:
This PBI cannot be completed until the following PBI has been completed: 
[Settings Page - Shell](https://github.com/orgs/COSC481W-2023Fall/projects/4/views/1?pane=issue&itemId=42822759)
