### ISSUE TITLE
Add a task feature - Recurring tasks

### ISSUE THREAD

**Issue by moorhead212** [COSC481W-2023Fall/planned-out#54]
**User story:**
As a user, I would like to be able to set a **recurring task**. The recurring task will then populate my tasks at the rate I specify out to the end date I specify. (See: [Kyle Beta testing, "other feedback" line 12c](https://docs.google.com/document/d/1do8CKjxs9zATaoVYpmA1HocePQAKmZDZKqxBaMDrH10/edit))

- **Persona:** A user adding a task that will occur at a specific rate out to a specific end date.
- **Fix/Feature:** Create a recurring feature to allow multiple tasks to be added all at once over a specific period of time. 
- **Business Value:** Allowing users easier use of adding recurring tasks will increase their productivity and their willingness to use our product.

**Tasks:**
- [ ] Add recurring option (check box opens a new section?)
- [ ] Add recurring rates (daily, weekly, monthly)
- [ ] Add recurring start/end dates option (might limit the "end date" so that we don't have 5000 tasks added at once)
- [ ] Update the task add route in server.mjs to accommodate the new feature.
- [ ] Automatically create tasks in database based on the rate specified by user out to end date

**Acceptance criteria:**
- [ ] Adding a task with "recurring" will add the tasks to the database out to the "end" date specified by user.
