### ISSUE TITLE
Friends page

### ISSUE THREAD

**Issue by moorhead212** [COSC481W-2023Fall/planned-out#56]
**User story:**
As a user, I would like to be able to add friends and compare my stats to theirs. The friends page should exist and allow me to do that.

- **Persona:** A user that wants to compete with friends and gamify completing tasks.
- **Fix/Feature:** Create a friends page that allows people to connect and share progress.
- **Business Value:** Allowing users to have friends increases the chance that they will keep using the app to compete.

**Tasks:**
- [x] Add frontend for friends page
- [x] Add backend for friends page
- [x] Allow the user to add a friend based on username
- [x] Allow the user to see how many tasks their friends have completed compared to them

**Acceptance criteria:**
- [x] The friends page exists and functions
- [x] A user can add a friend based on username
- [x] A user can click on their friend on the friends page to compare stats
