### ISSUE TITLE
Settings - Profile Picture

### ISSUE THREAD

**Issue by moorhead212** [COSC481W-2023Fall/planned-out#57]
**User story:**
As a user, I would like to be able to set a profile picture. (See [Ted Gravlin Beta Testing report](https://docs.google.com/document/d/1nRsWqgP6FMtiOmN4eehJwwMO5zNDPfbvwqQ47Gvao5Q/edit?usp=sharing))

> They clicked ‘Profile’
Nothing was there, and they were confused why clicking on profile picture didn’t do anything. They really wanted to be able to set a profile picture of some sort.

- **Persona:** A user that wants to customize their profile by choosing a profile picture.
- **Fix/Feature:** Add several avatar options that the user can choose from
- **Business Value:** Allowing users to choose a profile picture makes it more likely that they use the app more often as it's more personalized.

**Tasks:**
- [ ] Create avatar options
- [ ] Create frontend for Settings - Profile Picture
- [ ] Create backend for Settings - Profile Picture

**Acceptance criteria:**
- [ ] A user can choose from one of the preset profile pictures
- [ ] Selecting a profile picture creates a reference to it in the user's account
