### ISSUE TITLE
User- Add on-screen Alert for tasks

### ISSUE THREAD

**Issue by moorhead212** [COSC481W-2023Fall/planned-out#60]
**User story:**

As a user, I would like a reminder to appear on-screen when my task is scheduled to begin or is due. 

[Link:](https://docs.google.com/document/d/1C9YP48RrqiqPUX2o2UWQECi2d9gz-rsVKZ3b8cvHjQE/edit)

- Persona : A user wants a reminder to do a task without having to look.
- Fix/Feature : Added alert that will appear on screen when approaching scheduled time or day.
- Business Value : Updating users on-screen will allow for ability to turn a user's attention elsewhere on the page and improve productivity over time. 
 
**Tasks:**

- [ ] Add alert to tasks
- [ ] Give user option to add alert.

**Acceptance Criteria:**

- [ ] Allowing users the option to alert them when tasks are about to occur. 
- [ ] Allowing for users to look away for a minute or two and turn attention elsewhere.
