### ISSUE TITLE
Task List - Display Task Description

### ISSUE THREAD

**Issue by moorhead212** [COSC481W-2023Fall/planned-out#61]
**User story:**
As a user, I would like to be able to see the description I wrote for a task. 
(See: [Kyle Beta testing, "other feedback" line 4a](https://docs.google.com/document/d/1do8CKjxs9zATaoVYpmA1HocePQAKmZDZKqxBaMDrH10/edit))

> "Noted description does not show up with the task
Suggested click on task to open description"

- **Persona:** A user viewing the details of their tasks.
- **Fix/Feature:** Create a box to display the task description on task click.
- **Business Value:** Allowing users to see more information about their task will lead to them being more likely to return for future use. 

**Tasks:**
- [x] Add click function to task list item.
- [x] Add text box with text description.
- [x] Open text box on click.

**Acceptance criteria:**
- [x] Click on a task list item will open a text box with the current items description.
