### ISSUE TITLE
Stats page - front end

### ISSUE THREAD

**Issue by moorhead212** [COSC481W-2023Fall/planned-out#62]
**User Story:**
User should be taken to dedicated Stats page upon clicking on stats page

- Persona: User wanting to view personal stats related to tasks and their completion.
- Fix/Feature: Create page to display graph of user's personal task stats.
- Business Value: Allows user to see their individual data on tasks, completed, total number.

**Beta testing reference**

"There’s no feedback when clicking Friends and Stats tabs. Should at least lead to new page with “Work in progress” message"
Report link: https://docs.google.com/document/d/1E4ukcXI_H9eUJjKXfB4XNCreuWboAOuZ-L73OXnXzMM/edit

**Tasks:** 

- [ ] Create stats page
- [ ] Link page to Stats tab
- [ ] Create cards for graphs/data
- [ ] Create card for option buttons
- [ ] Create option buttons

**Acceptance criteria**

- [ ] Clicking on Stats page leads to new page with two cards, one for graph, one for options
