### ISSUE TITLE
Home Page - Task View - Frontend/Backend

### ISSUE THREAD

**Issue by Locobird00** [COSC481W-2023Fall/planned-out#9]
As a user, I should be able to view my tasks for a given day. 

### TASKS

- [ ] The task view should show the name of the selected day
- [x] The task view should show all of the tasks for the day
- [x] There should be a checkbox next to the tasks that indicates whether or not the task has been completed
- [x] Clicking the checkbox should mark the task as solved

### HOW THIS SHOULD WORK

- After a new task has been added for the user in the database, show the task in the view
- After task has been completed, the task will have a strikethrough and grayed out
- Tasks that have not been crossed off, will show on top while completed ones will show below
- If a user unchecks a task, it will not be strikethrough and not be grayed out
